### ISSUE TITLE
烤鸭：你好！

### ISSUE THREAD

**Issue by yangyi860** [sskyNS/RoastDuck-CFWPack#6]
烤鸭你好，用你的包一段时间了，很好用，让彻底吃灰的switch重新焕发生机，成为客厅的一道亮丽风景线，也成了跟孩子一起娱乐成长的一个很重要的方式。从b站上了解到你的遭遇，很遗憾，但是你的退出决定是对的，支持你，做事情如何危及到自己的安危了，确实放弃也无碍，即便我以后也再用不到你的包了，但还是真心谢谢你！

**Comment by sskyNS** [comment]
**感谢你，我陌生的朋友！即使我不再与这些事情包裹在一起，但我真心为我的CFW Pack曾经给你带来的快乐感到高兴！**
`Thank you, my friend. Even though I am no longer wrapped up in these things, I am truly happy for the joy my CFW Pack once brought you!`

我的朋友们已经为我带来了最公正的评判，这场比赛没有胜者，没有原始意义的裁判，因为真相在每一个人心中。

`My friends have brought me the most fair judgment. There is no winner in this game, no original referee, because the truth is in everyone's heart.`
